services:
  - type: web
    name: esgi-render-2i1-kumo
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    runCommand: npm run start
    env:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: esgi-render-2i1-kumo
          proprerty: connectionString
databases:
  - name: esgi-render-2i1-kumo
    region: frankfurt
    plan: free